MDBoxLayout:
	adaptive_height: False

	MDBottomNavigation:

		MDBottomNavigationItem:

			text: "Logga"
			name: "logga"
			icon: "account-circle"
			BoxLayout:
                pos_hint: {'center_x': .5}
				orientation: 'vertical'
				MDLabel:
					id:response
					text:"Jag vill logga:"

                BoxLayout:
                    orientation: 'horizontal'


                    MDRaisedButton:
                        text: "Transport"
                        pos_hint:{'center_x': 0, 'center_y': .5 }
                        md_bg_color: 0,0,0,.5
                        on_press: app.trans_press()

                    MDRaisedButton:
                        text: "Mat"
                        pos_hint:{'center_x': 0, 'center_y': .5 }
                        md_bg_color: 0,0,0,1
                        on_press: app.mat_press()


				MDTextField:
					id: input
					hint_text:"Hej"
				MDFillRoundFlatButton:
					text_color: 1, 1, 1, 1
					text:"korv"
					on_press: app.press()

		MDBottomNavigationItem:
			text: 'Se din p\u00e5verkan'
			name: "se"
			icon: "account-cash"
			BoxLayout:
				orientation: 'vertical'


		MDBottomNavigationItem:
			text: 'Se din historik'
			name: "se2"
			icon: "account-cash"
			BoxLayout:
