MDBoxLayout:
	adaptive_height: False

	MDBottomNavigation:

		MDBottomNavigationItem:

			text: "Logga"
			name: "logga"
			icon: "file-document"
			MDBoxLayout:



				orientation: 'vertical'

                MDToolbar:


                    elevation: 20
                    title: "Footprint"

                    md_bg_color: app.theme_cls.primary_color

				MDLabel:
					id:response
					text:"Jag vill logga:"
                    halign: "center"


                MDFloatLayout:



                    MDRaisedButton:
                        text: "Transport"
                        id: transknapp
                        md_bg_color: 1,1,1,1
                        on_press: app.trans_press()
                        pos_hint: {'x': .2, 'y': .7}


                    MDRaisedButton:
                        id: matknapp
                        text: "Mat"
                        pos_hint: {'x': .6, 'y':.7}
                        md_bg_color: 1,1,1,1
                        on_press: app.mat_press()

                MDLabel:
                    text:""
                    halign: "center"
                    id: translabel

                MDBoxLayout:
                    orientation:'horizontal'

				    MDTextField:
                        id: input
					    hint_text:"Hej"
				    MDFillRoundFlatButton:
                        text_color: 1, 1, 1, 1
					    text:"korv"
					    on_press: app.press()

		MDBottomNavigationItem:
			text: 'Se din p\u00e5verkan'
			name: "se"
			icon: "chart-line"
			BoxLayout:
				orientation: 'vertical'

                Image:
                    id: img
                    source: 'piechart.png'
                    size: self.texture_size

                MDRaisedButton:
                    md_bg_color: 1,1,1,1
                    text: 'uppdatera'
                    on_press: app.update()


		MDBottomNavigationItem:
			text: 'Inställningar'
			name: "se2"
			icon: "cog"
			BoxLayout:
