MDBoxLayout:
	adaptive_height: False

	MDBottomNavigation:

		MDBottomNavigationItem:

			text: "Logga"
			name: "logga"
			icon: "account-circle"
			MDBoxLayout:


				orientation: 'vertical'
				MDLabel:
					id:response
					text:"Jag vill logga:"
                    halign: "center"


                MDFloatLayout:

                    md_bg_color: app.theme_cls.primary_color

                    MDRaisedButton:
                        text: "Transport"
                        id: transknapp
                        md_bg_color: 0,0,0,.5
                        on_press: app.trans_press()
                        pos_hint: {'center_y': .5, 'right': 1}


                    MDRaisedButton:
                        id: matknapp
                        text: "Mat"
                        pos_hint: {'center_y': .5, 'left': 1}
                        md_bg_color: 0,0,0,1
                        on_press: app.mat_press()


                MDBoxLayout:
                    orientation:'horizontal'

				    MDTextField:
                        id: input
					    hint_text:"Hej"
				    MDFillRoundFlatButton:
                        text_color: 1, 1, 1, 1
					    text:"korv"
					    on_press: app.press()

		MDBottomNavigationItem:
			text: 'Se din p\u00e5verkan'
			name: "se"
			icon: "account-cash"
			BoxLayout:
				orientation: 'vertical'


		MDBottomNavigationItem:
			text: 'Se din historik'
			name: "se2"
			icon: "account-cash"
			BoxLayout:
